function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function complimentGenerator() {
    const her = document.getElementById("her");
    const compliments = [
	"Eye contact with you always feels like foreplay",
        "Your smile lights up the room.",
        "You have the most infectious laughter.",
        "Your kindness is truly admirable.",
        "Your intelligence is a constant inspiration.",
        "I love the way you make me see the world differently.",
        "You have a fantastic sense of humor.",
        "Your positive energy is contagious.",
"Do you know how many times I’ve mentally stripped you",
        "Your creativity knows no bounds.",
        "I appreciate the unique perspective you bring to every conversation.",
        "Your passion for life is evident in everything you do.",
        "You have a captivating presence.",
        "Your generosity is heartwarming.",
        "Your thoughtfulness always makes my day.",
        "I'm constantly amazed by your talents.",
        "Your warmth and sincerity are truly special.",
        "Your sense of style is impeccable.",
        "I'm grateful for the joy you bring into my life.",
        "Your determination is truly inspiring.",
        "Your optimism is like a ray of sunshine.",
"Do you know how many times I’ve mentally stripped you",
        "I love how you always find the good in every situation.",
        "Your strength, both mentally and emotionally, is commendable.",
        "You have a way of making people feel seen and heard.",
        "Your humility is a rare and beautiful trait.",
        "I admire the way you handle challenges with grace.",
        "Your sense of adventure is exhilarating.",
        "You have a heart of gold.",
        "Your ability to empathize with others is remarkable.",
"Eye contact with you always feels like foreplay",
        "Your dedication to personal growth is admirable.",
        "I'm impressed by your resilience in the face of adversity.",
        "Your honesty and authenticity are refreshing.",
        "Your positive attitude is a beacon of light.",
        "You have an incredible ability to make others feel valued.",
        "Your wisdom far surpasses your years.",
"Your very presence makes me want to be tender",
        "Your generosity knows no bounds.",
"I want to eat you out until I’ve memorized every single pink fold of flesh",
        "Your perseverance in pursuing your goals is inspiring.",
        "Your sense of humor never fails to brighten my day.",
"Your very presence makes me want to be tender",
        "Your gentle spirit is a calming presence.",
        "I love how you always bring out the best in people.",
        "Your ability to see the beauty in the little things is a gift.",
"Your very presence makes me want to be tender",
        "Your friendship is one of the greatest blessings in my life.",
        "Your dedication to making a difference is admirable.",
        "Your integrity is truly commendable.",
        "I appreciate the way you always lend a helping hand.",
"Eye contact with you always feels like foreplay",
        "Your humility is a breath of fresh air.",
        "Your commitment to personal excellence is inspiring.",
        "Your perseverance in the face of challenges is truly inspiring.",
        "I'm grateful for your unwavering support and encouragement.",
        "Your ability to find solutions to problems is impressive.",
"Do you know how many times I’ve mentally stripped you",
        "Your sense of adventure and willingness to try new things is admirable.",
        "Your dedication to your passions is truly inspiring.",
        "Your positive outlook on life is contagious.",
        "Your compassion towards others is heartwarming.",
        "Your authenticity is a rare and beautiful trait.",
        "I'm continually inspired by your commitment to personal growth.",
        "Your ability to stay calm under pressure is impressive.",
        "Your presence brings joy to those around you.",
        "Your ability to make others feel valued is a rare and beautiful gift.",
        "Your courage to be yourself is truly admirable.",
        "I appreciate the way you always find the silver lining.",
        "Your commitment to excellence sets you apart.",
        "Your sense of responsibility and reliability is truly commendable.",
        "Your creativity knows no bounds.",
"I want to eat you out until I’ve memorized every single pink fold of flesh",
        "Your ability to adapt to new situations is impressive.",
        "Your humility in the face of success is truly refreshing.",
        "Your dedication to your goals is truly inspiring.",
        "Your positive energy is a light in my life.",
        "Your ability to find joy in the little things is admirable.",
        "Your willingness to help others is truly heartwarming.",
        "Your resilience in overcoming challenges is truly inspiring.",
"Do you know how many times I’ve mentally stripped you",
        "Your sense of humor and wit make every moment more enjoyable.",
        "Your warmth and kindness make you a truly special person.",
        "Your dedication to personal growth is truly admirable.",
        "Your ability to find joy in the little things is contagious.",
        "Your authenticity and genuineness shine through in everything you do.",
        "Your commitment to making a positive impact is commendable.",
"Do you know how many times I’ve mentally stripped you",
        "Your kindness and compassion make the world a better place.",
        "Your sense of humor brings so much joy to those around you.",
        "Your ability to find beauty in the ordinary is truly special.",
        "Your resilience in the face of challenges is inspiring.",
        "Your positive attitude is contagious.",
"Do you know how many times I’ve mentally stripped you",
        "Your commitment to personal development is truly commendable.",
        "Your thoughtfulness towards others is truly heartwarming.",
        "Your ability to stay calm and composed is impressive.",
        "Your dedication to your craft is truly inspiring.",
        "Your generosity knows no bounds.",
"I want to eat you out until I’ve memorized every single pink fold of flesh",
        "Your ability to make others feel valued is a rare and beautiful gift.",
        "Your courage to be authentic is truly admirable.",
        "Your sense of adventure and curiosity make life more exciting.",
        "Your kindness towards others is a reflection of your beautiful soul.",
        "Your perseverance in the pursuit of your dreams is truly impressive.",
        "Your humility in the face of success is truly commendable.",
        "Your positive energy is a source of inspiration.",
        "Your commitment to making a difference is truly commendable.",
        "Your willingness to lend a helping hand is truly appreciated.",
        "Your resilience in overcoming challenges is truly inspiring.",
        "Your sense of humor and wit make every moment more enjoyable.",
"I want to eat you out until I’ve memorized every single pink fold of flesh",
        "Your warmth and kindness make you a truly special person.",
        "Your dedication to personal growth is truly admirable.",
"Do you know how many times I’ve mentally stripped you",
        "Your ability to find joy in the little things is contagious.",
        "Your authenticity and genuine nature make you a true gem."
    ];

    const randomIndex = getRandomInt(0, compliments.length - 1);
    const randomCompliment = compliments[randomIndex];

    her.innerHTML = "<h1 id='her'>" + randomCompliment + "<h1>";
}

// Example usage:
complimentGenerator();
